### ISSUE TITLE
Can I hide some commands' stack frame output in a flow?

### ISSUE THREAD

**Issue by wzru** [innerr/ticat#230]
Just like `ticat dummy : tidb.new`. Can I hide the stack frame output of `dummy`? 
When the flow grows up, the stack frame prints too much. So I wonder if there is some way to hide some inessential outputs.

**Comment by innerr** [comment]
For `*.ticat` or `*.tiflow` files, we could use `pack-subflow = true` to totally hide all output:
```
# sample.tiflow
help = just a sample
flow = dummy : tidb.new
pack-subflow = true
```

For ad-hot flow, we could use `display.quiet`:
```
$> ticat display.quiet : dummy : tidb.new
```

**Comment by innerr** [comment]
```
ticat display.stack.off : dummy : tidb.new
```
