### ISSUE TITLE
Why does ticat use yet another DSL instead of reusing unix pipe?

### ISSUE THREAD

**Issue by tisonkun** [innerr/ticat#8]
I can see with ticat we recreate a TiDB cluster by

```
$ ticat db.rm : db.new
```

It looks quite like the unix pipe style, but use `:` and we do create yet another DSL.

I'd like to know the technical considerations behind this design; otherwise I'd prefer as less DSL to learn as possible.

BTW, you might consider [enable GitHub Discussion](https://docs.github.com/en/discussions/quickstart) for cases like this one, since it is not quite an issue to be resolved but an open question.

**Comment by innerr** [comment]
I will write a doc about this later :)

**Comment by tisonkun** [comment]
@innerr any updates?

**Comment by tisonkun** [comment]
I can see a number of docs landed, and maybe [this section](https://github.com/innerr/ticat/blob/main/doc/zen.md#sequence-vs-unix-pipe) is related.

**Comment by innerr** [comment]
I wrote a small doc for this https://github.com/innerr/ticat/blob/main/doc/zen/why-not-pipe.md

**Comment by tisonkun** [comment]
Thanks! Closing as resolved...
